### ISSUE TITLE
New release for PyPI?

### ISSUE THREAD

**Issue by markpeek** [kimgr/asn1ate#17]
I have some asn1 that fails with 0.4 (the version from PyPI) but works with the latest master. It would be easier for some of my co-workers to install from PyPI than using git clone. Do you have any schedule or plans to update the version on PyPI?

Thanks,
Mark

**Comment by kimgr** [comment]
Hi Mark,

I'm terribly behind on asn1ate, but I'd like to get something out sooner rather than later.

There are two things in the way:

- The few open issues, I'd like to get them fixed before I release anything new
- We maintain internal code generators that build on asn1ate's parser and sema libraries, and I'd like to make sure I can update them to work with the trunk release before I release it.

I realize that none of this is helpful to you directly, but hopefully I can get something relatively stable out. Good to know there's interest, I'll try and work on it with more priority.

**Comment by markpeek** [comment]
Hi Kim,
Thank you for reply. I totally understand the need to wrap up a release with fixed issues and ensuring it works with your internal code. Yes, there is definitely interest by us in using your project in a code generator we built (which we hope to open source in the future). Thank you for making the code available and for looking into doing a new release in the future.

Thanks,
Mark

**Comment by markpeek** [comment]
Sorry to bother you again. Any progress on a new release?

**Comment by kimgr** [comment]
Sort of :-)

I started closing issues, and I think I'll let the last one slide, because I don't think it's the right way to solve the problem.

As for our code generators, I haven't had time to look at them, but I won't block the release on that. We can always take that hit when we upgrade from PyPI internally.

So I'll try to make an effort to get this out before Monday. Ping me again if I slip :-)

**Comment by kimgr** [comment]
I managed: https://pypi.python.org/pypi/asn1ate/0.5

Hope that helps!

**Comment by markpeek** [comment]
Worked great. Thank you very much!
